### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by blondegeek** [afonari/emc#5]
Hi Alexandr,
How would you like your code cited in publications?
Thanks!
Tess

**Comment by blondegeek** [comment]
Just found the citation note in the README.pdf --- would you like there to be a link as part of the citation? Such as a link to this repository?

**Comment by afonari** [comment]
Something like this: A. Fonari and C. Sutton, Effective Mass Calculator for Semiconductors, http://afonari.com/emc/.

would work, thanks!

**Comment by blondegeek** [comment]
Thanks for the reply. I get a 404 error when I link to that page.

**Comment by afonari** [comment]
Yeah. I'll fix it soon.

**Comment by blondegeek** [comment]
Great. Thanks again!
